language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - phpenv rehash
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind gdb

install:
  - ext/install

before_script:
  - echo 'extension="bee.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - ulimit -c unlimited || true

script:
  - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full phpunit --debug
